### ISSUE TITLE
Missing /ebp [Personal Backpack View]

### ISSUE THREAD

**Issue by DarrienZ** [PluginBugs/Issues-EpicBackpacks#105]
**Describe the bug**

**To Reproduce**
No Error 
Command to open Personal Backpack not working. 

**Screenshots**
![image](https://github.com/PluginBugs/Issues-EpicBackpacks/assets/108975040/25ade91f-f52a-4df6-ade3-f39a752af0a0)

**Info (please complete the following information):**
 - Server version: (Pufferfish version git-Pufferfish-27 (MC: 1.20.1)
 - Client version: 1.20.2 Optifine (Original Minecraft Launcher)
 - Plugin version: EpicBackpacks version 1.3.16-r5

**Comment by LoneDev6** [comment]
Possible causes:
- another plugin is using the same ebp command, so it overrides it
- you don't have ebp permission
