### ISSUE TITLE
No Commands are working

### ISSUE THREAD

**Issue by Thangsss** [PluginBugs/Issues-EpicBackpacks#106]
EpicBackpacks_1.3.16-r5
Itemsadder_3.6.2-beta-r2
This server is running Paper version git-Paper-249 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 996d529)
You are running the latest version
Previous version: git-Paper-241 (MC: 1.20.2)

Upon server start I get this message

`28.10 17:16:06 [Server] ERROR Could not pass event ItemsAdderFirstLoadEvent to EpicBackpacks v1.3.16-r5
28.10 17:16:06 [Server] INFO java.lang.NullPointerException: Cannot invoke "org.bukkit.profile.PlayerProfile.getTextures()" because "ownerProfile" is null
28.10 17:16:06 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:148) ~[paper-1.20.2.jar:git-Paper-249]
28.10 17:16:06 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:659) ~[paper-1.20.2.jar:git-Paper-249]
28.10 17:16:06 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:632) ~[paper-1.20.2.jar:git-Paper-249]
28.10 17:16:06 [Server] INFO at dev.lone.EpicBackpacks.a.a(SourceFile:275) ~[EpicBackPacks_1.3.16-r5.jar:?]
28.10 17:16:06 [Server] INFO at dev.lone.EpicBackpacks.i.d(SourceFile:191) ~[EpicBackPacks_1.3.16-r5.jar:?]
28.10 17:16:06 [Server] INFO at dev.lone.EpicBackpacks.Main.d(SourceFile:176) ~[EpicBackPacks_1.3.16-r5.jar:?]
28.10 17:16:06 [Server] INFO at dev.lone.EpicBackpacks.k.a(SourceFile:22) ~[EpicBackPacks_1.3.16-r5.jar:?]
28.10 17:16:06 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
28.10 17:16:06 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-249]
28.10 17:16:06 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
28.10 17:16:06 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-249]
28.10 17:16:06 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-249]
28.10 17:16:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
28.10 17:16:06 [Server] INFO at ia.m.lr.a(SourceFile:73) ~[ItemsAdder_3.6.2-beta-r2.jar:?]
28.10 17:16:06 [Server] INFO at ia.m.G.c(SourceFile:883) ~[ItemsAdder_3.6.2-beta-r2.jar:?]
28.10 17:16:06 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-249]
28.10 17:16:06 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-249]
28.10 17:16:06 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470) ~[paper-1.20.2.jar:git-Paper-249]
28.10 17:16:06 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-249]
28.10 17:16:06 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-249]
28.10 17:16:06 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-249]
28.10 17:16:06 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-249]`

When in game, no command is working what so ever, it just spits out the command back at me
![2023-10-28_13 37 56](https://github.com/PluginBugs/Issues-EpicBackpacks/assets/111655899/479e5bae-91c2-4a78-af07-a07e661c4f60)

Everything was good until I updated paper

**Comment by LoneDev6** [comment]
- update to the latest paper version
- update to the latest lonelibs version
- remove any custom skin plugin you have
- try to remove all other plugins and see if the error still occurs
Let me know, thanks

**Comment by Thangsss** [comment]
I updated paper to latest and everything seems fine now
