### ISSUE TITLE
[Suggestion] personal backpack

### ISSUE THREAD

**Issue by qwe938775** [PluginBugs/Issues-EpicBackpacks#13]
When the personal backpack starts with ebp.user.size.18 and fills up the item,
After changing to ebp.user.size.9, 9 items disappeared. It is recommended to change (automatically return items). When the items are full and fall on the ground.

Use MYSQL

**Comment by LoneDev6** [comment]
if you set ebp.user.size.18 again will the items appear?

I prefer not to make the items fall on the ground.. it's not a good solution since they can get stolen

**Comment by qwe938775** [comment]
They will appear again

My server will change its permissions to ebp.user.size.9 when the time is up. I want to use it as a task reward
