### ISSUE TITLE
[BUG] Unable to Autopickup Items

### ISSUE THREAD

**Issue by Reese14** [PluginBugs/Issues-EpicBackpacks#15]
**Describe the bug**
When items are on the ground, and you pick them up, it does automatically put them in a backpack. However, when you mine a block and autopickup from my prison plugin is enabled, the items do not go into a backpack.

**To Reproduce**
1. Enable autopickup
2. Mine a block

**Expected behavior**
When you mine a block, the items should go into a backpack instead of just your inventory.

**Info (please complete the following information):**
 - Server version: Spigot 1.16.5
 - Client version: vanilla 1.16.4
 - Plugin version: v1.2.9)

**Additional context**
- Prison plugin is UltraPrisonCore

**Comment by Reese14** [comment]
I need help please? This is currently holding me back from opening up my prison server!

Thank you!

**Comment by LoneDev6** [comment]
Hello, seems that UltraPrisonCore autopickup is interfering with my plugin.
I can't fix it on my code as it's a UltraPrisonCore problem, they have to check if my plugin has autopickup enabled but it's difficult to do, I see no solution for that issue other than ask the other plugin author to contact me directly on Discord
