### ISSUE TITLE
Add variable

### ISSUE THREAD

**Issue by HoneyBearc** [PluginBugs/Issues-EpicBackpacks#17]
lore
Can this variable be added?
or %player_name%
![2021-03-05_02 32 07](https://user-images.githubusercontent.com/42526263/110125028-d2193f80-7dfd-11eb-8407-2cb5aca13962.png)

**Comment by LoneDev6** [comment]
will be added in the next update.
you will be able to set the %player_name% variable of PlaceholderAPI. This will be updated only on craft or give command tho, not when a user drops backpack to another player
