### ISSUE TITLE
[Suggestion] option for empty backpacks to be stored/not stored in ender chests

### ISSUE THREAD

**Issue by EvanBl** [PluginBugs/Issues-EpicBackpacks#25]
**Is your feature request related to a problem? Please describe.**
I like that I can choose whether I can put away backpacks in enderchests, but I also want to be able to choose if empty backpacks can be put into ender chests
**Describe the solution you'd like**
I would like there to be an option for empty backpacks to be stored/not stored in ender chests, and an option for filled backpacks to be stored/not stored in ender chests
**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by LoneDev6** [comment]
This will be added in the next update

```yml
allow_put_empty_backpacks_in_enderchest: true
allow_put_empty_backpacks_in_shulkerboxes: true
```
