### ISSUE TITLE
[BUG] Epic Back Packs Duping Contents Using Chestsort Hotkeys

### ISSUE THREAD

**Issue by Zykana** [PluginBugs/Issues-EpicBackpacks#27]
I'm having a bug that Epic Back Packs dupes a contents when emptying with a hotkey and using ChestSort.

**Expected behavior**
Expected the backpack to simply empty into the inventory.

**Info (please complete the following information):**
 - Server version: Spigot 1.17 (f773da8-f81f499) 1.17-R0.1-Snapshot
 - Plugin version: Chestsort: 10.3.1, EPIC BackPacks 1.3.5

**Comment by LoneDev6** [comment]
Is this still valid with the latest Chestsort?

**Comment by LoneDev6** [comment]
Strange.
Be sure to update:
- lonelibs
- epicbackpacks
- chestsort

**Comment by Zykana** [comment]
It seems it is now fixed!

**Comment by LoneDev6** [comment]
Very good :D
I hope you'll consider leaving a 5 stars review, this will help me a lot!
Thanks for your time
