### ISSUE TITLE
[BUG] Pre-Filled Backpacks missing contained items

### ISSUE THREAD

**Issue by laceee29** [PluginBugs/Issues-EpicBackpacks#28]
**Describe the bug**
When I save a pre-filled backpack then I get it by /ebpget the backpack's inventory is empty. However in backpack.yml contains all the items that should be in it.

**Info (please complete the following information):**
 - Server version: tryed 1.16.5 and 1.17 as well
 - Plugin version: 1.3.5

**Additional context**
Backpack.yml looks like this:

backpacks:
vip_filled:
    enabled: true
    display_name: '&b&lVIP &fBackpack'
    can_auto_pickup: false
    show_in_menu: false
    item:
      type: HEAD
      texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWYyM2YxMTVjYjk1MjBkZDRkNGNiMjkxMjRkYWJhYzVlNjg0NGY5NmNjZTI0MWEzZWM5Y2E2ZjdhMjk2MjQ3In19fQ==
      lore:
      - '&6[ &eVIP &6Backpack ]'
    size: 3
    blacklist:
    - BARRIER
    - BEDROCK
    sounds:
      open:
        name: ENTITY_ENDER_DRAGON_FLAP
        volume: 1
        pitch: 0.5
      close:
        name: ENTITY_ENDER_DRAGON_FLAP
        volume: 1
        pitch: 0.5
      auto_pickup:
        name: ENTITY_ITEM_PICKUP
      click:
        name: ENTITY_ITEM_FRAME_ADD_ITEM
    contents:
      slot_4: TOTEM_OF_UNDYING:x1
      slot_11: ENDER_PEARL:x1
      slot_13: ENDER_PEARL:x1
      slot_15: ENDER_PEARL:x1
      slot_21: ENCHANTED_GOLDEN_APPLE:x1
      slot_23: WANDERING_TRADER_SPAWN_EGG:x1

**Comment by LoneDev6** [comment]
can you send me the configuration file? drag and drop it here.
It's hard to read the pasted text as it lost the indentation

**Comment by laceee29** [comment]
> can you send me the configuration file? drag and drop it here.
> It's hard to read the pasted text as it lost the indentation

d

**Comment by laceee29** [comment]
Omg I closed it by mistake..

I had to change the file extension to be able to drop it here..
[backpacks.txt](https://github.com/PluginBugs/Issues-EpicBackpacks/files/6749373/backpacks.txt)

**Comment by LoneDev6** [comment]
![image](https://user-images.githubusercontent.com/27242001/125463396-1cb34ce0-c0df-4b2c-806e-494b84a35bc2.png)
