### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: de/jeff_media/chestsort/Sortable

### ISSUE THREAD

**Issue by DrakMC** [PluginBugs/Issues-EpicBackpacks#29]
Describe the bug
With ChestSort version 11.0.0 Epic Backpacks doesn't work due to API changes.

Info (please complete the following information):
Server version: Purpur 1.16.5
Client version: OptiFine 1.16.5
Plugin version: 1.3.5
Additional context
Error: https://pastebin.com/raw/SqzaUpQ5

**Comment by LoneDev6** [comment]
Did they change the API again?
I already updated the compatibility some weeks ago.
Try to update ChestSort and EpicBackpacks to the latest version

**Comment by DrakMC** [comment]
They changed API again.
