### ISSUE TITLE
[Suggestion] click item into backpack

### ISSUE THREAD

**Issue by SugarDaddii** [PluginBugs/Issues-EpicBackpacks#3]
[NEW FEATURE]

Is it possible when you have a item on your cursor and you don’t want to open the backpack that you only click with the item on your backpack and it will put it inside?
Like click and drop!

**Comment by LoneDev6** [comment]
Cool suggestion, but it will result bad when users try to swap items, they will be sucked into the clicked backpack.
Do you still think is a good feature? I think users will complain
