### ISSUE TITLE
[BUG] Backpacks put in Enderchest

### ISSUE THREAD

**Issue by Pyario** [PluginBugs/Issues-EpicBackpacks#32]
**Describe the bug**
If you use the command / ec or / enderchest to open the enderchest and take a backpack from the inventory you can click (or sometimes you have to click several times in the Enderchest inventory to do that ...) in the enderchest the item join the enderchest. I deactivated it so that you can put it in the enderchest..

**To Reproduce**
1. Enter /ec from EssentialsX or with your own plugin 
2. Take the backpack that is in the inventory in hand
3. With the backpack in hand, click into a free slot in the Enderchest (sometimes you have to click several times, but most of the time you can do it with one click)
4. You have a Backpack in Enderchest...

**Expected behavior**
I have no idea how to fix it, I think you can think of something.

**Screenshots**
Video: https://www.youtube.com/watch?v=gai3sA9jBuE

**Info (please complete the following information):**
 - Server version: purpur-1.17.1-1329
 - Client version: 1.17.1
 - Plugin version: 1.3.6

**Comment by Pyario** [comment]
Please fix that! :)

**Comment by LoneDev6** [comment]
Thanks, I'm working on a fix
