### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by BlueSky-fur** [PluginBugs/Issues-EpicBackpacks#33]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**

Maybe add an option so we can set custom timers for opening backpacks.

for example a small gymbag takes 3 seconds to open, and a large coyotebackpack takes 5 seconds to open, basically an option in the backpacks.yml where we can set a timer.

and then maybe if you are in the opening process and switch to another item it stops opening it

would absolutely love to see that :D

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by LoneDev6** [comment]
Good idea! Will be added in the next update

**Comment by BlueSky-fur** [comment]
Awesome! 

keep up the good work!
