### ISSUE TITLE
[Bug] Duplication bug 1.8.9

### ISSUE THREAD

**Issue by GeistFighter** [PluginBugs/Issues-EpicBackpacks#34]
**Describe the bug**
Hello, there is a duplication bug with EpicBackPack

**To Reproduce**
To perform the duplication bug you need:
take the BackPack in your hand;
Put an object in it;
Close it;
Open it again and take the object with the mouse but do not put it down;
get killed by a friend;

**Expected behavior**
Result: the object falls out and the BackPack keeps the object inside!

**Info (please complete the following information):**
 - Server version: 1.8.9
 - Client version: 1.8.9
 - Plugin version: 1.3.6

**Comment by GeistFighter** [comment]
The way to solve this bug is:
- either to make the BackPack update when you move the items in the inventory (and not once the inventory is closed), and also to make it update when a player picks up the item with the BackPack mouse.

-Or make sure that the BackPack does not drop

**Comment by GeistFighter** [comment]
But, the second option is simplicity

**Comment by LoneDev6** [comment]
Thanks a lot for the report, I will fix it ASAP
