### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by CloWnicide** [PluginBugs/Issues-EpicBackpacks#35]
**Is your feature request related to a problem? Please describe.**
Automatic pickups with EBP and UltimateStacker will only pickup 32 items out of a stack lager than 64 items.

**Describe the solution you'd like**
The backpacks be able to collect all items from the floor.

**Additional context**
![2021-08-31_02 32 38](https://user-images.githubusercontent.com/27911500/131537367-61bc3e8a-68a8-4b39-a409-f8885a521476.png)
![2021-08-31_02 32 52](https://user-images.githubusercontent.com/27911500/131537379-163137e6-1c09-4062-b018-ff541c9a59aa.png)

**Comment by LoneDev6** [comment]
Thanks, this will be added in the next update
