### ISSUE TITLE
[Suggestion] Backpack Opening Timer in Actionbar

### ISSUE THREAD

**Issue by BlueSky-fur** [PluginBugs/Issues-EpicBackpacks#36]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Since we now have the Option for an open-delay it would be cool if that would be displayed in the actionbar when using `use_actionbar_for_messages`

**Describe alternatives you've considered**
None.

**Comment by LoneDev6** [comment]
Will be fixed, thanks!
