### ISSUE TITLE
[Suggestion] RoseStacker compatibility

### ISSUE THREAD

**Issue by CloWnicide** [PluginBugs/Issues-EpicBackpacks#39]
Same as the last ticket I opened about UltimateStacker, can there be compatibility for RoseStacker and EpicBackpacks? Items are only automatically picked up to a full stack of 64 items, anything further gets deleted.

https://www.spigotmc.org/resources/rosestacker.82729/
https://github.com/Rosewood-Development/RoseStacker

**Comment by ProfessionalBoatDrifter** [comment]
We use RoseStacker. Was this ever updated?

**Comment by EnVoImMav** [comment]
@LoneDev6
