### ISSUE TITLE
plugin crash while reloading /ebpreload

### ISSUE THREAD

**Issue by EMlerrx13** [PluginBugs/Issues-EpicBackpacks#43]
**_### According to the topic I wrote_**
I want to know why this happened. So how can this be fixed now?
see error https://pastebin.com/R6PRTCEB

**Comment by LoneDev6** [comment]
rename the jar file to `EpicBackPacks.jar`

**Comment by EMlerrx13** [comment]
ok i know why it has to do with the folder name do not omit the spacebar
