### ISSUE TITLE
[BUG] Dupe EpicBackPacks

### ISSUE THREAD

**Issue by InsaneTomas** [PluginBugs/Issues-EpicBackpacks#44]
**Describe the bug**
You can ezz dupe any items!

**To Reproduce**
https://www.youtube.com/watch?v=0c3LwqJk6F4

**Expected behavior**
Sorry i dont understand :D

**Screenshots**
https://www.youtube.com/watch?v=0c3LwqJk6F4

**Info (please complete the following information):**
 - Server version: Purpur 1.17.1
 - Client version: Lunar client 1.17.1
 - Plugin version: 2.0.9

**Additional context**

**Comment by InsaneTomas** [comment]
It not working only on anvil it working on crafting table chest furnaces and more

**Comment by LoneDev6** [comment]
Thanks I identified the issue and a fix is planned :D
