### ISSUE TITLE
[BUG] Could not pass event PlayerInteractEvent 

### ISSUE THREAD

**Issue by Bronzwar** [PluginBugs/Issues-EpicBackpacks#45]
**Describe the bug**
After install new version i got this error

**To Reproduce**
https://paste.helpch.at/qecehulalo.cs

**Screenshots**
none

**Info (please complete the following information):**
 - Server version: kSpigot 1.12.2.
 - Client version:  1.12.2.
 - Plugin version: 1.3.10

**Comment by warzoneak** [comment]
i also am having this issue same server version + newest plugin version 1.3.12

**Comment by LoneDev6** [comment]
Thanks, this will be fixed
