### ISSUE TITLE
[BUG] EpicBackpacks loads before ItemsAdder

### ISSUE THREAD

**Issue by toneelspeler** [PluginBugs/Issues-EpicBackpacks#46]
**Describe the bug**
On startup, EpicBackpacks loads before ItemsAdder.

**To Reproduce**
1. Startup the server

**Expected behavior**
EpicBackpacks loads up before ItemsAdder, causing it to fail ItemsAdder items.

**Info (please complete the following information):**
 - Server version: paper 1.17.1
 - Plugin version: ItemsAdder 2.4.23, and EpicBackpacks v1.3.10

**Additional context**
I fixed the issue by opening plugins.yml in EpicBackpacks.jar and changing
```
depend:
   - LoneLibs
```
to
```
depend:
   - LoneLibs
   - ItemsAdder
```

**Comment by LoneDev6** [comment]
It's strange since EpicBackpacks has ItemsAdder as `softdepend` in the configuration.
I cannot add it to the `depend` list or it won't be enabled on servers without ItemsAdder
