### ISSUE TITLE
[Suggestion] CustomModelData Support

### ISSUE THREAD

**Issue by lucian929** [PluginBugs/Issues-EpicBackpacks#47]
**Is your feature request related to a problem? Please describe.**
I use a custom fork of another custom items plugin for my server, so we cannot use the [itemsadder compatibility ](https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/epicbackpacks) feature.

**Describe the solution you'd like**
Ability to define the CustomModelData for the backpack in the config.

**Describe alternatives you've considered**
Using a default minecraft item instead of a custom one :(

**Additional context**
n/a

**Comment by LoneDev6** [comment]
It's already possible, please check the wiki
https://epicbackpacks.devs.beer/configurations/skin#vanilla-item-with-custommodeldata
