### ISSUE TITLE
[Suggestion] Disable lore lines that show content of the backpacks

### ISSUE THREAD

**Issue by RobZenTL** [PluginBugs/Issues-EpicBackpacks#49]
Hey, great work in all your plugins!
My wish is that there is an option to disable the lore, where a backpack shows what is inside. We want to use the pre-generated backpacks for some rare kind of "mystery loot" and if the lore shows all the content of the backpack, that doesn't work. Also big lores aren't that beautiful in our eyes, so when a player has a full backpack, thats a massive lore.

So the idea was that there is a config option to disable the function that the backpack content is written into the lore.
You could also give every single backpack this option, for me it would be enough to have a general config option to enable/disable this feature.

Thank you for your time and have a great day!

**Comment by LoneDev6** [comment]
Currently you can set a custom lore for your backpacks.
![immagine](https://user-images.githubusercontent.com/27242001/156735674-2546b60e-4d52-4aae-8cf8-0554efe72820.png)

A list of items will be added as soon as the player saves the backpack for the first time tho.
![immagine](https://user-images.githubusercontent.com/27242001/156735758-fae9ae90-89fe-4ab9-96c6-fbd06f273909.png)

**Comment by RobZenTL** [comment]
Sure, my suggestion would be to add a config option that this "list of items" is not written into the lore, even after using the backpacks. If possible, of course. Thanks for your help!

**Comment by LoneDev6** [comment]
A new global setting will be added: `show-backpacks-content-in-lore`

**Comment by RobZenTL** [comment]
Thank you very much! Appreciate it. Keep doing great work :)

**Comment by LoneDev6** [comment]
no problem! :D
