### ISSUE TITLE
[BUG] Inventory click

### ISSUE THREAD

**Issue by SaintGearz** [PluginBugs/Issues-EpicBackpacks#51]
[[**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Server version: (example: paper 1.15.2)
 - Client version: (example: fabric 1.15.2)
 - Plugin version: (example: 2.0.9 do not write "latest")

**Additional context**
](https://pastebin.com/8ffUFZUD)](https://pastebin.com/8ffUFZUD)
Mohist unfortunately but I would still love to use this for my pixelmon, happens on any inventory move/click, even switching between hotbar slots

**Comment by SaintGearz** [comment]
previous link expired: https://pastebin.com/ZQZ7UqN4

**Comment by LoneDev6** [comment]
Will be fixed in the next update
