### ISSUE TITLE
[BUG] Console Error - Crashes Server Eventually

### ISSUE THREAD

**Issue by OAFACraft** [PluginBugs/Issues-EpicBackpacks#52]
15.02 22:12:52 [Server] ERROR Could not pass event PlayerInteractEvent to EpicBackpacks v1.3.12
15.02 22:12:52 [Server] INFO java.lang.NullPointerException: Cannot invoke "dev.lone.EpicBackpacks.l.a()" because "<local2>" is null
15.02 22:12:52 [Server] INFO at dev.lone.EpicBackpacks.d.b(SourceFile:228) ~[EpicBackPacks.jar:?]
15.02 22:12:52 [Server] INFO at dev.lone.EpicBackpacks.d.a(SourceFile:263) ~[EpicBackPacks.jar:?]
15.02 22:12:52 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
15.02 22:12:52 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-105]
15.02 22:12:52 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
15.02 22:12:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
15.02 22:12:52 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[paper-1.18.1.jar:git-Paper-105]
15.02 22:12:52 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:506) ~[paper-1.18.1.jar:git-Paper-105]
15.02 22:12:52 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:501) ~[paper-1.18.1.jar:git-Paper-105]
15.02 22:12:52 [Server] INFO at net.minecraft.world.level.block.PressurePlateBlock.getSignalStrength(PressurePlateBlock.java:93) ~[?:?]
15.02 22:12:52 [Server] INFO at net.minecraft.world.level.block.BasePressurePlateBlock.checkPressed(BasePressurePlateBlock.java:82) ~[?:?]
15.02 22:12:52 [Server] INFO at net.minecraft.world.level.block.BasePressurePlateBlock.entityInside(BasePressurePlateBlock.java:75) ~[?:?]
15.02 22:12:52 [Server] INFO at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.entityInside(BlockBehaviour.java:966) ~[?:?]
15.02 22:12:52 [Server] INFO at net.minecraft.world.entity.Entity.checkInsideBlocks(Entity.java:1412) ~[paper-1.18.1.jar:git-Paper-105]
15.02 22:12:52 [Server] INFO at net.minecraft.world.entity.Entity.tryCheckInsideBlocks(Entity.java:1148) ~[paper-1.18.1.jar:git-Paper-105]
15.02 22:12:52 [Server] INFO at net.minecraft.world.entity.Entity.move(Entity.java:1075) ~[paper-1.18.1.jar:git-Paper-105]
15.02 22:12:52 [Server] INFO at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:2804) ~[?:?]
15.02 22:12:52 [Server] INFO at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2759) ~[?:?]
15.02 22:12:52 [Server] INFO at net.minecraft.world.entity.player.Player.travel(Player.java:1599) ~[?:?]
15.02 22:12:52 [Server] INFO at net.citizensnpcs.nms.v1_18_R1.entity.EntityHumanNPC.h(EntityHumanNPC.java:504) ~[Citizens-2.0.29-b2470.jar:?]
15.02 22:12:52 [Server] INFO at net.citizensnpcs.nms.v1_18_R1.entity.EntityHumanNPC.moveWithFallDamage(EntityHumanNPC.java:403) ~[Citizens-2.0.29-b2470.jar:?]
15.02 22:12:52 [Server] INFO at net.citizensnpcs.nms.v1_18_R1.entity.EntityHumanNPC.l(EntityHumanNPC.java:178) ~[Citizens-2.0.29-b2470.jar:?]
15.02 22:12:52 [Server] INFO at net.citizensnpcs.nms.v1_18_R1.util.NMSImpl.playerTick(NMSImpl.java:1003) ~[Citizens-2.0.29-b2470.jar:?]
15.02 22:12:52 [Server] INFO at net.citizensnpcs.util.NMS.playerTick(NMS.java:461) ~[Citizens-2.0.29-b2470.jar:?]
15.02 22:12:52 [Server] INFO at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:56) ~[Citizens-2.0.29-b2470.jar:?]
15.02 22:12:52 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-105]
15.02 22:12:52 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-105]
15.02 22:12:52 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-105]
15.02 22:12:52 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-105]
15.02 22:12:52 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-105]
15.02 22:12:52 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-105]
15.02 22:12:52 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-105]
15.02 22:12:52 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

Any idea what could be the cause?

**Comment by OAFACraft** [comment]
Downloaded plugin, restarted server.
Opened a backpack, then closed it. 
Reset for daily reset.
Next day, console errors with server crashed.

**Comment by LoneDev6** [comment]
I doubt the crash is related to this little error, maybe something else is triggering the crash.
Anyway it will be fixed in the next update, thanks!
