### ISSUE TITLE
[BUG] Disappearing/duping items with open backpacks directly from inventory

### ISSUE THREAD

**Issue by AfkF24** [PluginBugs/Issues-EpicBackpacks#53]
**Describe the bug**

**To Reproduce**
1. Right click a backpack in your inventory to open it
2. Place an item inside and close it with ESC
3. Notice that there's no closing sound after you've done that
4. Disconnect from the server
5. Items have disappeared

**Expected behavior**
The backpack should be properly closed and items should be saved.

**Screenshots**
/

**Info (please complete the following information):**
 - Server version: Paper 1.18.1, build 207
 - Client version: Vanilla 1.18.1
 - Plugin version: 1.3.12

**Additional context**
_The same technique can be used for **duping items**. Will record a video if needed. The main issue is that the plugin doesn't register that the backpack has been closed if opening it from directly your inventory, which leads to series of other issues._

**Comment by nivcoo** [comment]
Same issue here https://github.com/PluginBugs/Issues-EpicBackpacks/issues/48 , the plugin doesn't get correctly the inventory close event so the BP isn't save until you open another inventory and close it.

**Comment by LoneDev6** [comment]
Will be fixed in 1.3.13
