### ISSUE TITLE
Quickshop glitch

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-EpicBackpacks#55]
https://youtu.be/MH3I_ytNAz8

**Comment by AfkF24** [comment]
This is basically #48 and #53

**Comment by LoneDev6** [comment]
Trying to identify what is the cause since I cannot reproduce it, strange.

**Comment by AfkF24** [comment]
> Trying to identify what is the cause since I cannot reproduce it, strange.

Could you try with the steps described in #53? I've had a 100% reproduction rate.

**Comment by LoneDev6** [comment]
Found out the cause, I'm going to release an update today, thanks for the patience
