### ISSUE TITLE
[BUG] Backpacks don’t drop on death

### ISSUE THREAD

**Issue by adelando** [PluginBugs/Issues-EpicBackpacks#56]
Even having `disable_drop_backpacks: true` In the config, backpacks seem to always drop and aren’t in inventories upon respawning.

Using latest build, 1.3.12

Software version: git-Purpur-1547 (MC:
1.18.1)

![52B64103-8A99-42AD-8E80-D794145B545B](https://user-images.githubusercontent.com/11265974/156760860-9957085f-bf7d-461a-a83e-0fe40529cff8.jpeg)

![564E7795-0E3B-4276-9C70-5DA3D427B262](https://user-images.githubusercontent.com/11265974/156760849-3305cbbe-8419-47d9-96ac-419e295f3f78.jpeg)

**Comment by SirCraftypants** [comment]
Tested an can confirm whether true or false, the backapcks drop, i'm wondering if EBP already has the attribute keep_on_death like Itemsadder that can be used for individual backpacks in the backpack.yml or not?

**Comment by adelando** [comment]
Just tested with version 1.3.13 and git-purpur-1574 (MC: 1.18.2) and still the same issue

**Comment by adelando** [comment]
tested this also and it doesn’t work for EpicBackpacks

![DA1AF96F-7572-4078-B996-9028C30882DF](https://user-images.githubusercontent.com/11265974/156794634-1d99b45a-78c4-4bca-b656-33db8810f5da.jpeg)

**Comment by adelando** [comment]
Any updates?

**Comment by LoneDev6** [comment]
Seems to be a bug introduced by an update of Spigot.
I'll work on this in the next days, thanks for the patience

**Comment by adelando** [comment]
Thanks LoneDev!
