### ISSUE TITLE
[BUG] Losing the backpack

### ISSUE THREAD

**Issue by DrakMC** [PluginBugs/Issues-EpicBackpacks#57]
**Describe the bug**
Players can lose a backpack by placing it in an open backpack.

**To Reproduce**
1. Put your backpack into other hand.
2. Open backpack by right click
3. Point the mouse at a free slot in an open backpack
4. Press F
5. Close inventory 

**Expected behavior**
The backpack should not be able to be moved into the backpack.

**Info (please complete the following information):**
 - Server version: Purpur 1.17.1
 - Client version: Minecraft 1.18.2
 - Plugin version: 1.3.13

**Comment by MrJorman** [comment]
the same problem. It is necessary to somehow prohibit dragging a backpack using the letter F from the second hand.
