### ISSUE TITLE
[BUG] I can craft vanilla items from backpacks

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-EpicBackpacks#59]
I made a backpack material: paper and material: netherite_scrap, because I made a non-cerite backpack that does not burn, but if you put the backpacks in crafting, then they are considered as vanilla materials. see the screenshot.

![image](https://user-images.githubusercontent.com/55187962/157043140-122300de-aa17-4e08-bd11-47bd4f295d38.png)

**Comment by adelando** [comment]
Minecraft will always see it as a vanilla valid recipe when using the same recipe and materials (even tho it’s a custom model it still is netherite scrap)

**Comment by MrJorman** [comment]
in ItemsAdder this problem - fixed.
