### ISSUE TITLE
[BUG] Can't use backpacks command and inventory error

### ISSUE THREAD

**Issue by SaintGearz** [PluginBugs/Issues-EpicBackpacks#60]
Inventory close error: https://pastebin.com/MxMNSRYc

Attempted /ebp error: https://pastebin.com/PZrf0jfa

MC VER: 1.12.2
Jar: Mohist (For Pixelmon, don't hate me)
Plugin VER: 1.3.13

**Comment by LoneDev6** [comment]
Do you have `ChestSort` installed? If yes, please update it.

About the error `Could not pass event InventoryCloseEvent to EpicBackpacks v1.3.13` I have to do some tests, seems Mohist has some issues.
Keep in mind that this plugin wasn't coded to work with every possible unofficial Spigot fork, sadly most of these forks break plugins.
I'll try to add compatibility.

**Comment by SaintGearz** [comment]
Thank you, and okay I'll update it, I'll even delete it if need be. But this is the best backpack plugin for my situation and would love for it to work, thank you LD
