### ISSUE TITLE
[Suggestion] Different display-name for CHEST GUI than item

### ISSUE THREAD

**Issue by Golicraft** [PluginBugs/Issues-EpicBackpacks#63]
**Is your feature request related to a problem? Please describe.**
Just that it doesn't follow our server theme. 

**Describe the solution you'd like**
I would like an option to set different names in the CHEST GUI and the display-name

**Describe alternatives you've considered**
None, I don't think it is. 

**Additional context**
I hope this can be added. It really breaks my server layout/theme and doesn't look great.

**Comment by Golicraft** [comment]
![image](https://user-images.githubusercontent.com/11066952/162516466-330eb15f-09ff-4fc0-be72-151e9235d6d0.png)

**Comment by Golicraft** [comment]
Hi @LoneDev6. Can I know your thoughs on this?

**Comment by LoneDev6** [comment]
I don't clearly understand what is the precise suggestion.

**Comment by Golicraft** [comment]
> Hi @LoneDev6. Can I know your thoughs on this?

![image](https://user-images.githubusercontent.com/11066952/163652638-420c56c7-5bf7-4017-ae77-3bb48be6562e.png)
The suggestion is that we can have a own GUI title and not use the name of the item.

**Comment by Golicraft** [comment]
Example config can be to add this chest_gui_display_name: "&rRegular backpack"

  regular:
    enabled: true
    display_name: '&6&lRegular backpack &7(&fRight click&7)'
    chest_gui_display_name: "&rRegular backpack" # <-- NEW | The name that appears in the GUI

**Comment by Golicraft** [comment]
So, @LoneDev6. Can I know your thoughs on this now as you understand what I mean?

**Comment by LoneDev6** [comment]
Basically you're asking a "item display name" and a "gui display name" right?

**Comment by Golicraft** [comment]
> Basically you're asking a "item display name" and a "gui display name" right? What would I show as name in the backpacks recipes preview? Maybe a third title would be needed? I think is not good showing "Red Backpack (right click)" as name in the recipes view, so maybe a third title would be good.

Yes, agree! This would be a very needed and necessary feature of your plugin for us to use it (and probably a lot more people). We really need everything to fit our custom layout. Thank you for your understanding :)

**Comment by LoneDev6** [comment]
Next update will implement that new feature `display_name_gui`
```yml
backpacks:
  example_1:
    enabled: false
    display_name: '&fexample'
    display_name_gui: "&fexample backpack"
```
