### ISSUE TITLE
[BUG]  ERROR in console upon disconnection

### ISSUE THREAD

**Issue by nullasciz** [PluginBugs/Issues-EpicBackpacks#66]
Error message shows on console upon player disconnection. 
Players do not have backpack or /ebp open while disconnected.

PaperMC 1.18.1 (git-Paper-216)
Vanilla 1.18.1 (1.18.1-OptiFine_HD_U_H4)
EpicBackPacks 1.3.14

[ebp_error_report.txt](https://github.com/PluginBugs/Issues-EpicBackpacks/files/8501030/ebp_error_report.txt)

**Comment by CloudeLecaw** [comment]
Same as here
https://github.com/PluginBugs/Issues-EpicBackpacks/issues/64

I recommend for now to downgrade to 1.3.13

Pls try to read others bugs reports before next time the bug now is reported in 3 different following issues ;)
