### ISSUE TITLE
[BUG] 1.17+ Item Names

### ISSUE THREAD

**Issue by Sixsoul** [PluginBugs/Issues-EpicBackpacks#67]
Anything added past 1.17 displays as "null" in the lore when in a backpack.

**Comment by LoneDev6** [comment]
![image](https://user-images.githubusercontent.com/27242001/211350734-b3fff1c5-8cef-46cf-97c9-9e262952d5c3.png)
It works fine for me, tested on Paper 1.19.3.

Maybe you have to update LoneLibs.

Anyway next update should fix this kind of issues using clientside translations.
