### ISSUE TITLE
[BUG] PlayerDeathEvent

### ISSUE THREAD

**Issue by alechretien16** [PluginBugs/Issues-EpicBackpacks#68]
Hello. When killing a Citizens npc an error occurs on the console. I use Citizens for compatibility with bosses of the npc type with Boss™.

 - Server version:  Purpur 1.18.2.
 - Client version: fabric 1.18.2
 - Plugin version: 1.3.15

Log: https://pastebin.com/uUQn20ym

**Comment by LoneDev6** [comment]
![image](https://user-images.githubusercontent.com/27242001/211301330-79839d07-5223-4744-ab3e-b464ebcfd6a0.png)
Please repost the log, thanks.
