### ISSUE TITLE
[BUG] Backpacks stack and become unusable

### ISSUE THREAD

**Issue by Sixsoul** [PluginBugs/Issues-EpicBackpacks#69]
**Describe the bug**
When empty, backpacks can stack. When they stack, players can't unstack them or open them or anything so they become unusable.

**To Reproduce**
1. Give a player 2 of the same backpack.
2. Realize they can no longer open them or unstack them, or anything.

**Expected behavior**
Backpacks can't stack.

**Comment by nivcoo** [comment]
Same issue here

**Comment by LoneDev6** [comment]
How do you generate these items?
You are not supposed to change the backpacks item amount.
Use the command /iaget to generate more.

If you need to create a premade backpack use the built-in feature: https://epicbackpacks.devs.beer/configurations/pre-filled-backpacks
