### ISSUE TITLE
[BUG] Really easy item duplication

### ISSUE THREAD

**Issue by Sixsoul** [PluginBugs/Issues-EpicBackpacks#70]
**Describe the bug**
If a player opens a backpack with right click while in any other plugin GUI, they can remove items from the backpack with right click. Then when they exit the GUI they will have the items still in their backpack and in their inventory.  It's not a specific plugin incompatibility, I've tested it with 5+ plugins that use GUIs.

**Expected behavior**
A quick fix would be to just add an option that disables being able to open backpacks with right-click in inventory.

**Info (please complete the following information):**
 - Paper 1.18.2
 - Any client
 - Plugin version: 1.3.15

**Comment by LoneDev6** [comment]
Strangely this wasn't reported until now.
The plugin was heavily tested before. I also tried now and I can't manage to reproduce the issue.

## Video
(in the video I'm trying to right click to open, but as you can see it won't work, it just picks up the item).

https://user-images.githubusercontent.com/27242001/169525360-49cab187-9f49-4efe-b15f-b6d85e7c1c6a.mp4


I tested on a normal chest GUI and on the RPGBank GUI, I can't open the backpack here.

I have this check in my code:
```java
if(e.getView().getTopInventory().getHolder() != null && e.getView().getTopInventory().getType() != InventoryType.CRAFTING)
  return;
```

**Comment by LoneDev6** [comment]
I just noticed you updated your message stating something else compared to the original message which I only noticed now.
> right click while in any other plugin GUI,

So is this wrong? Is this bug happening only on trading GUIs?
