### ISSUE TITLE
[BUG] Some Bugs in Minecraft Version 1.12.2

### ISSUE THREAD

**Issue by TeQTabanca** [PluginBugs/Issues-EpicBackpacks#73]
**Describe the bug**
**Your plugin is giving an error because the "ChestShort" plugin supports versions 1.16 and higher. The ChestSort author has added previous versions to the overview section so that older versions can be downloaded.**

When using Minecraft 1.15 or below, please use version 11.5.6
When using Minecraft 1.13 or below, please use version [9.5.1](https://www.spigotmc.org/resources/chestsort-api.59773/download?version=390678)

**To Reproduce**
1. It throws an error in the console when using the "/ebp" command.
2. I get a backpack from the command "/ebpget <any backpack>" and when I try to use the backpack nothing happens and it throws an error in the console.
3. When I open the inventory and right click on the backpack, the text "Backpack is loading..." appears, nothing happens and the console does not give an error.
4. If I have a backpack in my inventory, when I try to throw an item on the ground, the message "Loading backpack..." appears and I cannot throw the item on the ground.
5. Although I delete the backpack in creative mode, when I try to throw the items on the ground, the message "Loading the backpack..." appears and I cannot throw the item on the ground.

**Expected behavior**
I want the plugin to work more stable.

**Info (please complete the following information):**
 - Server version: spigot 1.12.2
 - Client version: forge 1.12.2
 - Plugin version: 1.3.16

**Additional context**
### It throws an error in the console when using the "/ebp" command.

> [09:28:09 INFO]: TeqTabanca issued server command: /ebp
> [09:28:09 ERROR]: null
> org.bukkit.command.CommandException: Unhandled exception executing command 'ebp' in plugin EpicBackpacks v1.3.16
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
>         at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at java.lang.Thread.run(Thread.java:829) [?:?]
> Caused by: java.lang.NoClassDefFoundError: de/jeff_media/chestsort/api/ChestSortAPI
>         at dev.lone.EpicBackpacks.main.o.a(SourceFile:101) ~[EpicBackpacks-1.3.16.jar:?]
>         at dev.lone.EpicBackpacks.main.o.onCommand(SourceFile:59) ~EpicBackpacks-1.3.16.jar:?]
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         ... 15 more
> Caused by: java.lang.ClassNotFoundException: de.jeff_media.chestsort.api.ChestSortAPI
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:476) ~[?:?]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
>         at dev.lone.EpicBackpacks.main.o.a(SourceFile:101) ~[EpicBackpacks-1.3.16.jar:?]
>         at dev.lone.EpicBackpacks.main.o.onCommand(SourceFile:59) ~[EpicBackpacks-1.3.16.jar:?]
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         ... 15 more

### I get a backpack from the command "/ebpget <any backpack>" and when I try to use the backpack nothing happens and it throws an error in the console.

> [09:50:02 WARN]: [EpicBackpacks] Plugin EpicBackpacks v1.3.16 generated an exception while executing task 32297
> java.lang.NoClassDefFoundError: de/jeff_media/chestsort/api/ChestSortAPI
>         at dev.lone.EpicBackpacks.a.a(SourceFile:367) ~[EpicBackpacks-1.3.16.jar:?]
>         at dev.lone.EpicBackpacks.d.a(SourceFile:140) ~[EpicBackpacks-1.3.16.jar:?]
>         at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
>         at java.lang.Thread.run(Thread.java:829) [?:?]
> Caused by: java.lang.ClassNotFoundException: de.jeff_media.chestsort.api.ChestSortAPI
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:476) ~[?:?]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
>         ... 7 more

**Comment by LoneDev6** [comment]
This is an issue caused by ChestSort author continuously changing their API despite the fact that an API is meant not to change during time (or at least have backwards compatibility).

I'll try to see if I can add support for multiple ChestSort versions but this is overkill.
