### ISSUE TITLE
Add support for UltimateCore-Collection

### ISSUE THREAD

**Issue by Hysteriox** [PluginBugs/Issues-EpicBackpacks#74]
Hello ! I'm using EpicBackPack and I would like to add support for a new plugin: UltimateCore-Collection. It's a plugin that copies the hypixel skyblock collections and I created with the backpacks a system that automatically collects the farm items to put them in, problem : it doesn't add a collection because the plugin is not supported / compatible with each other. Is there a possibility to add it ? Thank <3

**Comment by LoneDev6** [comment]
I don't own the plugin, I cannot add support
