### ISSUE TITLE
[BUG] Possible to place backpack into its own storage

### ISSUE THREAD

**Issue by adamboof** [PluginBugs/Issues-EpicBackpacks#76]
**Describe the bug**
While trying to recreate another bug I discovered that you are able to place the backpack item into its own inventory, resulting in it being lost to the void.

**To Reproduce**
1. Open a backpack
2. Shift+Left Click continuously
3. Press ESC or E to close inventory
4. If timed correctly, the backpack will be gone.

**Expected behavior**
You shouldn't be able to place a backpack inside another backpack, full stop

**Info (please complete the following information):**
 - Server version: paper 1.19.2 (example: paper 1.15.2)
 - Client version: 
 - Plugin version: 1.3.16-r1

**Additional context**

**Comment by adamboof** [comment]
On further testing, the backpack reappears if you interact with another backpack

**Comment by adamboof** [comment]
This appears to be a visual bug with the backpack icon in the inventory not being visible but still interactable

**Comment by LoneDev6** [comment]
Visual bugs are caused by desync of the server and are not harmful.
Provide a video for me to understand what happens, but I doubt I can fix it.

**Comment by adamboof** [comment]
Honestly, this was so long ago it genuinely doesn't matter to me anymore.

I don't use this plugin anymore due to the poor support.
