### ISSUE TITLE
[BUG] Using ChestSort on the hotbar while adding items to backpack

### ISSUE THREAD

**Issue by adamboof** [PluginBugs/Issues-EpicBackpacks#78]
**Describe the bug**
When putting items into the backpack and then using ChestSort on the hotbar, moving the position of the backpack, causes the items added to be lost.

**To Reproduce**
1. Add items to backpack
2. Shift + Left Click on the hotbar, causing the backpack to change position
3. Close backpack
4. On reentering backpack, you'll see items are missing

**Expected behavior**
Shifting the position of the backpack should not cause a loss of items.

**Info (please complete the following information):**
 - Server version: paper 1.19.2
 - Client version:
 - Plugin version: 1.3.16-r1

**Additional context**

**Comment by LoneDev6** [comment]
This seems to be a bug of ChestSort, I'll try to see if I can reproduce it and possibly find a solution.
