### ISSUE TITLE
[BUG] backpacks in shulkers with hoppers bug

### ISSUE THREAD

**Issue by Ekmot276** [PluginBugs/Issues-EpicBackpacks#8]
disable_put_in_shulkerboxes: true

does NOT prevent players from putting backpacks into shulker boxes using hoppers etc

**Comment by LoneDev6** [comment]
This decision was made to avoid doing too many checks and slow down the server, hoppers are heavy.
You may notice that if a player puts a backpack inside a shulker using a hopper something will happen: all backpacks will be dropped into the ground as soon as the user opens the shulker.

Let me know if this explaination is enough, thanks for the patience

**Comment by LoneDev6** [comment]
I added the feature as requested. I hope this doesn't cause too much CPU usage.
Consider updating your review, it would help a lot
