### ISSUE TITLE
The plugin doesnt work in 1.19.4  Please add support for it.

### ISSUE THREAD

**Issue by CloudeLecaw** [PluginBugs/Issues-EpicBackpacks#86]
**Describe the bug**
Well the plugin is loading and is shown green in list. But when nothing works what might be because its not really loaded.

**To Reproduce**
1. start the Server with Paper 1.19.4 and latest LoneLibs and Latest EpicPackpacks plugin.

**Expected behavior**
The plugin should work in 1.19.4

**Comment by LoneDev6** [comment]
Will be fixed, no plugin was currently updated to 1.19.4.

**Comment by LoneDev6** [comment]
Update LoneLibs to 1.0.24: https://www.spigotmc.org/resources/lonelibs.75974
And make sure you're running the latest EpicBackpacks too.
