### ISSUE TITLE
The backpack disappears

### ISSUE THREAD

**Issue by Lysity** [PluginBugs/Issues-EpicBackpacks#87]
The backpack disappears when you put it on your head.

I was about to play Minecraft but then the backpack I was trying to move to inventory just disappeared because I was trying to put it on my head

**Screenshots**

**Info (please complete the following information):**
 - Server version: 1.19.2
 - Client version: 1.19.2
 - Plugin version: 1.3.16-r3

https://user-images.githubusercontent.com/130282105/230765479-f85bee4a-f250-4c47-878a-72f04a594952.mp4

**Comment by LoneDev6** [comment]
Creative inventory has issues that can't be fixed because of how the game works, I can't control it.
Please always use backpacks in survival or avoid shift click in creative.
