### ISSUE TITLE
Hex Color works in Backpack Gui but not Physical Item

### ISSUE THREAD

**Issue by Frosty9999** [PluginBugs/Issues-EpicBackpacks#90]
Hello, I'm making this issue report today because when attempting to use hex color code on 1.19.4 I'm receiving two things. The first being that within the backpack Gui itself it appears correctly, the second being that the physical item in my inventory appears with the code but no color.

**Comment by LoneDev6** [comment]
It works just fine.
Example: `&x&b&d&e&a&a&0TEST`



![Image](https://github.com/PluginBugs/Issues-EpicBackpacks/assets/27242001/9845c307-ce3e-4b62-a54e-f4166e030191)



![Image](https://github.com/PluginBugs/Issues-EpicBackpacks/assets/27242001/73722085-bb5d-4876-8658-250feca9cd12)

**Comment by Frosty9999** [comment]
All good, we built our own exclusive to our needs.
