### ISSUE TITLE
[Suggestion] restrict player to put backpacks in bundles

### ISSUE THREAD

**Issue by NiceKaleido** [PluginBugs/Issues-EpicBackpacks#91]
**Is your feature request related to a problem? Please describe.**
User can work around the backpack limit by putting bundles in backpacks. 

**Describe the solution you'd like**
An Option similiar to restricting putting backpacks in shulker boxes but for bundles

**Describe alternatives you've considered**
There is none

**Comment by LoneDev6** [comment]
Added in the upcoming update:
```yml
disable_put_in_shulkerboxes: true
```

**Comment by NiceKaleido** [comment]
Thank you for adding it but it's for one broken .. putting an backpack in an bundle now deletes it and the bundle randomly copies itself. 

also why is it called like that? and not "disable_put_in_bundle"?

**Comment by LoneDev6** [comment]
I meant `disable_put_in_bundle`.
Anyway it was tested and working correctly, please add more details for example your server version and if you got any error.
Thanks!

Make a video of the issue, I cannot reproduce it on my server:
```
Paper version git-Paper-57 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 437e8da)

EpicBackpacks version 1.3.16-r4
```

https://github.com/PluginBugs/Issues-EpicBackpacks/assets/27242001/3064ab56-aef6-4c2d-abe1-885e3a20878d
