### ISSUE TITLE
Dupe Bug with Backpacks

### ISSUE THREAD

**Issue by RenatoPugaR** [PluginBugs/Issues-EpicBackpacks#92]
**Describe the bug**
This bug is a dupe glitch bug. When you update the plugin of ViaVersion to version 4.7.0 in order to support 1.20 or to use ViaBackwards, some users will just log in into the server and open their backpacks to withdraw their items, but when they open their backpacks again, the items will appear again inside the backpack and you can do that infinitely without any reason at all, only withdrawing items and they will continously respawn every time you open your backpack again. This only happens to some players and it is pretty random since the players that have this issue have no similarities between them. When I got back to the older version of ViaVersion (4.6.0), this wouldn't happen anymore. Also, if you try putting in other items to the backpack, they will just dissapear, like if it wasn't saving at all.

**To Reproduce**
1. Log in to the server with latest epicbackpacks version (1.3.16-r3) and latest viaversion version (4.7.0) on a network with waterfall and backend servers using purpur.
2. Open your backpack and if you are lucky enough, you can withdraw the items you had saved previously infinitely (since you can't put in new items in your backpacks).

**Expected behavior**
To use the backpacks normally.

**Info (please complete the following information):**
 - Server version: (example: Purpur #1735 [1.19] )
 - Client version: (example: Any client or version, it can be vanilla 1.16.5, lunar client 1.19.2, bedrock, vanila 1.19)
 - Plugin version: (example: Epic Backpacks 1.3.16-r3 and the use of ViaVersion 4.7.0)

**Comment by LoneDev6** [comment]
Please make a video showcasing how to reproduce the issue, thanks.
