### ISSUE TITLE
/ebpreload does not update Backpack configurations in-game

### ISSUE THREAD

**Issue by IAreKyleW00t** [PluginBugs/Issues-EpicBackpacks#93]
**Describe the bug**
When performing `/ebpreload` to update Backpack settings, these changes are **not** reflected until a full server restart is done. The reload command says it picks up all the backpacks, but none of the settings for it will change if you try to craft another one, or use it again. You will only see the changes after the server has restarted.

**To Reproduce**
1. Make changes to a backpack (eg: display name, sound, etc.) in the YAML config
2. Run the `/ebpreload` command
3. Check in-game and you will see changes are _not_ reflected
4. Restart server to see the changes

**Expected behavior**
The expected behavior is that any changes to the backpack configuration are reflected in-game as soon as the reload command is complete. It is **not** expected to have this retroactively updated backpacks in the cases of display name changes.

**Screenshots**
N/A - can provide more details if needed.

**Info (please complete the following information):**
 - Server version: git-Purpur-2006 (MC: 1.20.1)
 - Client version: Quilt 0.19.1 (MC: 1.20.1)
 - Plugin version: 1.3.16-r3

**Additional context**
- EBP Configs: https://gist.github.com/IAreKyleW00t/86b9fd5d7bb2b92eba6447ed4ddb1e7f
- Server plugins: AureliumSkills, BetterSleeping4, BossBarHealth, ChestSort, Chunky, CoreProtect, DecentHolograms, Elevator, EpicBackpacks, FastAsyncWorldEdit, floodgate, ForestPlant, Geyser-Spigot, GrapplingHook, Graves, GSit, InvUnload, LevelledMobs, LoneLibs, LuckPerms, LumberJack, PlaceholderAPI, ProtectionStones, ProtocolLib, QuickSave, spark, Vault, ViaBackwards, ViaVersion, WorldGuard

**Comment by LoneDev6** [comment]
I cannot reproduce the issue.
I renamed the backpack in the configuration file and the display name changed.
Already crafted backpacks won't change btw, it would require the plugin to scan the inventories and it's not a lightweight task.

https://github.com/PluginBugs/Issues-EpicBackpacks/assets/27242001/577f76a2-0960-4a9d-b95f-7d335f0c74da
