### ISSUE TITLE
/ebpreload causes events listener to be registered again

### ISSUE THREAD

**Issue by IAreKyleW00t** [PluginBugs/Issues-EpicBackpacks#94]
**Describe the bug**
Upon typing `/ebpreload`, whenever a users opens a backpack if theirs (whether new or already existing) the "Backpack is loading..." message is displayed every time until the server is fully restarted.

**To Reproduce**
1. Run the `/ebpreload` command while the server is running
2. In-game, open a backpack and you will see the "Backpack is loading..." message
3. Restart server to remove the issue

**Expected behavior**
The message is not displayed and operates normally like when the server first starts.

**Screenshots**
N/A - can provide more details if needed.

**Info (please complete the following information):**
 - Server version: git-Purpur-2006 (MC: 1.20.1)
 - Client version: Quilt 0.19.1 (MC: 1.20.1)
 - Plugin version: 1.3.16-r3

**Additional context**
- EBP Configs: https://gist.github.com/IAreKyleW00t/86b9fd5d7bb2b92eba6447ed4ddb1e7f
- Server plugins: AureliumSkills, BetterSleeping4, BossBarHealth, ChestSort, Chunky, CoreProtect, DecentHolograms, Elevator, EpicBackpacks, FastAsyncWorldEdit, floodgate, ForestPlant, Geyser-Spigot, GrapplingHook, Graves, GSit, InvUnload, LevelledMobs, LoneLibs, LuckPerms, LumberJack, PlaceholderAPI, ProtectionStones, ProtocolLib, QuickSave, spark, Vault, ViaBackwards, ViaVersion, WorldGuard

**Comment by ghost** [comment]
When is this fixed..? Experiencing the same issue
