### ISSUE TITLE
1.20.1 Support

### ISSUE THREAD

**Issue by Talesu** [PluginBugs/Issues-EpicBackpacks#96]
**Describe the bug**
When loading the plugin in version 1.20.1 the plugin doesn't start up

**Expected behavior**
The plugin starting up

**Info (please complete the following information):**
 - Server version: Pufferfish 1.20.1
 - Client version: Optifine 1.20.1
 - Plugin version: 1.3.16-r3

**Comment by LoneDev6** [comment]
Please post a log of when this happens

**Comment by BakiDance** [comment]
I don't have logs either, but can confirm that the plugin does not work in 1.20.1.

**Comment by LoneDev6** [comment]
Post a log

**Comment by BakiDance** [comment]
Don't have one
