### ISSUE TITLE
Duplication bug on death

### ISSUE THREAD

**Issue by energooooo** [PluginBugs/Issues-EpicBackpacks#98]
**Info (please complete the following information):**
 -  ![image](https://github.com/PluginBugs/Issues-EpicBackpacks/assets/68811273/3393aba6-be52-4f3c-b2cc-82861aa58a4c)
 - Client version: 1.16.5 fabric
 - Plugin version: 1.3.16-r3

https://youtu.be/HFoWne7H80o

**Comment by LoneDev6** [comment]
Please test on normal Spigot or Paper.
It might be a bug of Yatopia.

**Comment by LoneDev6** [comment]
I cannot reproduce the issue, it might be a Yatopia bug.
Backpack is automatically saved on death and no item is left behind.



https://github.com/PluginBugs/Issues-EpicBackpacks/assets/27242001/8e1539f6-6856-4de6-9a57-138083424180
