### ISSUE TITLE
Objects disappear from backpacks + dupe

### ISSUE THREAD

**Issue by Bauzamir13** [PluginBugs/Issues-EpicBackpacks#99]
**Info (please complete the following information):**
 - Server version: 1.18.2
 - Client version: 1.19.1 
 - Plugin version: 1.3.16-r3

Hi, users put objects in backpacks and when they close and reopen it, the objects have disappeared.

**Comment by Bauzamir13** [comment]
Hi, my users cant use bp beacuse this bug.
When it be solved pls?

**Comment by LoneDev6** [comment]
Hello,
Your report will be looked into as soon as possible, I'm just back from the summer break and I finally have access to my PC.
Rest assured that your questions won't be ignored.
Thanks a lot for the patience!

I cannot reproduce the issue.
Please make a video and provide a proper step by step guide for me to reproduce the issue, so that I can fix it.

**Comment by Bauzamir13** [comment]
Hi again,

I think I have found the source of the error.

As you can see in the video, when having any helmet on the head, the backpacks bug; causing that when placing objects in it disappear, and when taking out objects previously placed without having a helmet on, the objects are duplicated.

I hope I have explained me well and that it can be solved soon.

> https://youtu.be/df1-GUAGEHo

**Comment by LoneDev6** [comment]
Try in survival not creative.
Creative gamemode is known to have issues in this game.

**Comment by Bauzamir13** [comment]
Hi, It's exactly the same in survival.

By the way, I noticed that I get this error every time I reproduce the bug: https://pastebin.com/6BdecX7A

^ It should be noted that I just reproduced the bug with the default config of the plugin. I have even tried to play it on a different server (server version 1.18.2 too) and the exact same thing happens.

**Comment by LoneDev6** [comment]
Thanks, seems to be a duplicate of https://github.com/PluginBugs/Issues-EpicBackpacks/issues/101
